sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
build:
  exasolDbVersions:
    - "7.1.24"
    # Version 8 not yet supported, see https://github.com/exasol/cloudwatch-adapter/issues/91
