sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
linkReplacements:
  - "LICENSE-exasol-jdbc.txt|https://www.exasol.com/support/secure/attachment/155343/EXASOL_SDK-7.0.11.tar.gz"
