language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol

install:
  - .ci/install_sam.sh
  - cd sam/ && sam validate # remove!!!
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - cd sam/ && sam validate

cache:
  directories:
    - "$HOME/.m2"