AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: ExasolCloudWatchAdapter
    Description: This adapter transfers the statistics from the Exasol database to AWS CloudWatch metrics. This adapter runs independently of the Exasol database in an AWS Lambda function.
    Author: Exasol AG
    SpdxLicenseId: MIT
    LicenseUrl: ../LICENSE
    ReadmeUrl: ../README.md
    HomePageUrl: https://github.com/exasol/cloudwatch-adapter
    SemanticVersion: 1.0.7
    SourceCodeUrl: https://github.com/exasol/cloudwatch-adapter

Globals:
  Function:
    Timeout: 100

Parameters:
  Metrics:
    Type: "String"
    Description: "Comma separated list of the metrics to report. See https://github.com/exasol/cloudwatch-adapter for all available metrics."
    Default: "RAW_OBJECT_SIZE, MEM_OBJECT_SIZE, AUXILIARY_SIZE, STATISTICS_SIZE, RECOMMENDED_DB_RAM_SIZE, STORAGE_SIZE, USE, TEMP_SIZE, OBJECT_COUNT, LOAD, CPU, TEMP_DB_RAM, PERSISTENT_DB_RAM, HDD_READ, HDD_WRITE, LOCAL_READ_SIZE, LOCAL_READ_DURATION, LOCAL_WRITE_DURATION, CACHE_READ_SIZE, CACHE_READ_DURATION, CACHE_WRITE_SIZE, CACHE_WRITE_DURATION, REMOTE_READ_SIZE, REMOTE_READ_DURATION, REMOTE_WRITE_SIZE, REMOTE_WRITE_DURATION, NET, SWAP, USERS, QUERIES, NODES, DB_RAM_SIZE, EVENT_BACKUP_END, EVENT_BACKUP_START, EVENT_BACKUP_ABORTED, BACKUP_DURATION"
  ExasolDeploymentName:
    Type: "String"
    Description: "A name describing the Exasol installation you want to monitor. The adapter adds this name as a dimension to the metrics in cloudwatch. This will help you to distinguish the data if you monitor more than one Exasol deployment."
    MinLength: 1
  ExasolConnectionSecretArn:
    Type: "String"
    Description: "ARN of a SecretsManager secret with username, password, port and host of the Exasol database."
    MinLength: 1
  SubnetId:
    Type: "String"
    Description: "ID of the VPC subnet of the Exasol database."
    MinLength: 1
  SecurityGroup:
    Type: "String"
    Description: "ID of the security group of the Exasol database."
    MinLength: 1

Resources:
  ExasolCloudWatchAdapter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../target/exasol-cloudwatch-adapter.jar
      Handler: com.exasol.cloudwatch.CloudWatchAdapter
      Runtime: java11
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref SubnetId
      Environment:
        Variables:
          EXASOL_DEPLOYMENT_NAME: !Ref ExasolDeploymentName
          EXASOL_CONNECTION_SECRET_ARN: !Ref ExasolConnectionSecretArn
          METRICS: !Ref Metrics
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ExasolConnectionSecretArn
        - CloudWatchPutMetricPolicy: {}
        - VPCAccessPolicy: {}
      Events:
        MinutelyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Description: Minutely trigger for the CloudWatch adapter
            Enabled: True
            RetryPolicy:
              MaximumRetryAttempts: 0
              MaximumEventAgeInSeconds: 60
