name: Prepare SAM release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21
      - name: Install and configure
        run: |
          pip --only-binary :all: install awscli aws-sam-cli
          echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties
      - name: Build SAM package
        run: |
          mvn --batch-mode package -Dproject-keeper.skip=true -DossindexSkip=true
          cd sam
          sam package --s3-bucket persistent-cloudwatch-adapter-releases --region eu-central-1 > packed.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_ACCESS_KEY_ID }} # The user is defined by the ci-isolation stack.
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_SECRET_ACCESS_KEY }}
      - name: Upload packed template
        uses: actions/upload-artifact@v7
        with:
          name: packedTemplate
          path: sam/packed.yml
      - name: Create issue for manual release
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
