name: Prepare SAM release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install and configure
        run: |
          pip install awscli aws-sam-cli
          echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties
      - name: Build SAM package
        run: |
          mvn package
          cd sam
          sam package --s3-bucket persistent-cloudwatch-adapter-releases --region eu-central-1 > packed.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_ACCESS_KEY_ID }} # The user is defined by the ci-isolation stack.
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_SECRET_ACCESS_KEY }}
      - name: Upload packed template
        uses: actions/upload-artifact@v3
        with:
          name: packedTemplate
          path: sam/packed.yml
      - name: Create issue for manual release
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}